// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/DarkAIRenderMusicPlayer-7DvZpm/App.tsx": () => import("../components/mockups/templates/DarkAIRenderMusicPlayer-7DvZpm/App.tsx"),
  "./components/mockups/templates/LetterpressWorkshopHomeScreen--iMLDS/App.tsx": () => import("../components/mockups/templates/LetterpressWorkshopHomeScreen--iMLDS/App.tsx"),
  "./components/mockups/templates/LetterpressWorkshopHomeScreen-745ACR/App.tsx": () => import("../components/mockups/templates/LetterpressWorkshopHomeScreen-745ACR/App.tsx"),
  "./components/mockups/templates/LetterpressWorkshopHomeScreen-EFMfv6/App.tsx": () => import("../components/mockups/templates/LetterpressWorkshopHomeScreen-EFMfv6/App.tsx"),
  "./components/mockups/templates/LetterpressWorkshopHomeScreen-LTSvgE/App.tsx": () => import("../components/mockups/templates/LetterpressWorkshopHomeScreen-LTSvgE/App.tsx"),
  "./components/mockups/templates/LetterpressWorkshopHomeScreen-uMNVW7/App.tsx": () => import("../components/mockups/templates/LetterpressWorkshopHomeScreen-uMNVW7/App.tsx"),
  "./components/mockups/templates/PortraitDrivenAgencyLanding-37JVMC/Solene.tsx": () => import("../components/mockups/templates/PortraitDrivenAgencyLanding-37JVMC/Solene.tsx"),
  "./components/mockups/templates/PortraitDrivenAgencyLanding-IP-Yzh/Solene.tsx": () => import("../components/mockups/templates/PortraitDrivenAgencyLanding-IP-Yzh/Solene.tsx")
};
